name: Prettier Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier-check:
    name: Check Code Formatting with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.1
        with:
          version: 8.6.0

      - name: Use Dev Cache
        id: dev-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.dev-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run Prettier Check
        run: pnpm run prettier
